# Generated by Django 5.0.6 on 2026-01-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_html',
            field=models.BooleanField(default=False, help_text='Check if the content is in HTML format'),
        ),
    ]
