# Generated by Django 6.0 on 2026-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='graphical_content',
            field=models.TextField(blank=True, default='', help_text='HTML code for the graphical/infographic explanation (if any)'),
        ),
    ]
