# Generated by Django 5.0.6 on 2026-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default=0, help_text='Short summary for SEO description', max_length=500),
            preserve_default=False,
        ),
    ]
