# Generated by Django 6.0 on 2026-03-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_graphical_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this tag belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='posts.category'),
        ),
    ]
