# Generated by Django 6.0 on 2026-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(help_text='Short summary for SEO description', max_length=2000),
        ),
    ]
